export const ERROR_MESSAGE = {
  required: 'This field is required',
  maxLength: 'This field must be less than or equal to 20 characters',
  minLength: 'This field must be at least 6 characters',
  email: 'Please enter a valid email',
  passwordConfirm: 'Passwords must match',
  message: 'Error sending message',
  text: 'Text must be less than or equal to 500 characters',
  invalidUrl: 'Invalid URL',
  wrongPassword: 'Wrong password. Please try again.',
  genericError: 'Error. Please try again later.',
  unauthenticated: 'Unauthenticated. Please login again.',
  deletingError: 'An error occurred while deleting the profile.',
  googleSignIn: 'Error during Google sign-up',
  loadPosts: 'Error loading posts',
  invalidCred: 'Invalid credentials',
  signUp: 'Error signing up, try again',
  createComment: 'Error creating comment',
  update: 'Updating is failed',
  validFile: 'Please select a valid image file.',
  noFile: 'No file selected.'
};
